### ISSUE TITLE
[1.4.5] Error when installing fresh

### ISSUE THREAD

**Issue by ionesculiviucristian** [JeffreyWay/laravel-mix#1212]
- Laravel Mix Version: 1.4.5 (`npm list --depth=0`)
- Node Version (`node -v`): 8.5.0
- NPM Version (`npm -v`): 5.4.2
- OS: Ubuntu 16.04 LTS

### Description:

Unable to install node modules on fresh installation

### Steps To Reproduce:

My packages.json file:
```
{
  "private": true,
  "scripts": {
    "dev": "npm run development",
    "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch-poll": "npm run watch -- --watch-poll",
    "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "prod": "npm run production",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "devDependencies": {
    "axios": "^0.16.*",
    "bootstrap-sass": "^3.*",
    "cross-env": "^5.*",
    "jquery": "^3.*",
    "laravel-mix": "^1.4.5",
    "lodash": "^4.*",
    "node-sass": "^4.5",
    "vue": "^2.*",
    "webpack": "^3.6.0",
    "yargs": "^8.*"
  }
}
```

Output after npm install:
```
> node-sass@4.5.3 install /var/www/html/eoncms_0.7.x/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/liviu/.npm/node-sass/4.5.3/linux-x64-57_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /var/www/html/eoncms_0.7.x/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> node-sass@4.5.3 postinstall /var/www/html/eoncms_0.7.x/node_modules/node-sass
> node scripts/build.js

Binary found at /var/www/html/eoncms_0.7.x/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine

> mozjpeg@4.1.1 postinstall /var/www/html/eoncms_0.7.x/node_modules/mozjpeg
> node lib/install.js

module.js:529
    throw err;
    ^

Error: Cannot find module 'stream-shift'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/www/html/eoncms_0.7.x/node_modules/duplexify/index.js:4:13)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mozjpeg@4.1.1 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mozjpeg@4.1.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liviu/.npm/_logs/2017-09-20T09_46_17_197Z-debug.log
```

**Comment by ionesculiviucristian** [comment]
The above configuration works with version 1.4.3 of laravel mix.

**Comment by yansern** [comment]
Can't replicate. I tried with your package.json file and I can install just fine.
```
> mozjpeg@4.1.1 postinstall /Users/yansern/test-1212/node_modules/mozjpeg
> node lib/install.js
  ✔ mozjpeg pre-build test passed successfully
```

You might want to try `npm cache clean --force` and reinstall.

**Comment by ruchern** [comment]
@ionesculiviucristian `rm -rf node_modules` and install again using `npm install` or `yarn`.

**Comment by adridev** [comment]
Having the same error here. It seems to be related to https://github.com/imagemin/gifsicle-bin/blob/master/lib/install.js the package gifsicle@3.0.4 runs as its postinstall script and there is a permission denied error with the vendor/gifsicle binary that it tries to run(previously downloaded by the postinstall script).
