### PR TITLE
upgrade babel core and babel preset, fix vuejs unit tests

### LINKED ISSUE #2383: Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
-   Laravel Mix Version: 5.0.4 
-   Node Version: 13.13.0
-   NPM Version: 6.14.4
-   OS: macOS 10.15.4

I think this is related to a breaking change in node version 13.13 which conflicts with babel <= 7.9

### PR DESCRIPTION
**Pull request by yamenarahman**
Fixes #2383 
also fixed vuejs unit tests.

### CODE REVIEW

**Comment by cmosguy** [comment]
@JeffreyWay  this issue just bit me when i pulled in the latest docker image for my build pipeline.  I do not undrestand why the AppVeyer is failing, but you need to update the babel/preset-env to `7.9.0` for this to work with node version > `13.13`.

Thanks!
