### ISSUE TITLE
Autoload and extract are not working as expected

### ISSUE THREAD

**Issue by justkidding96** [JeffreyWay/laravel-mix#2684]
-   Laravel Mix Version: 6.0.0
-   Node Version: 12.18.3
-   NPM Version: 6.14.8
-   OS: macOS Big Sur 11.0.1

### Description:
Autoload and extract are not working as expected. Get the error is not a function.

### Steps To Reproduce:
Try to add slick-carousel and sweetalert2 to autoload and extracting.

**Comment by thecrypticace** [comment]
Can you please provide a reproduction repo?

**Comment by alperyazgan** [comment]
It is still not working with the version "laravel-mix@6.0.19";
Current solution is to include the statement `window.$ = require('jquery');` in the app.js

PS. It can be seen on a basic  laravel test project  with jetstream +  livewire is selected.

In webpack.mix.js:
```js
const mix = require('laravel-mix');
require('laravel-mix-clean');
// -------------------------------------------------------------------------
const projectPaths = {
  //baseSource      : 'resources/',
  publicSource    : 'resources/public-root/',
  jsSource        : 'resources/js/',
  cssSource       : 'resources/css/',
  baseDestination : 'public',
  jsDestination   : 'js',
  cssDestination  : 'css',
};
// -------------------------------------------------------------------------
mix.disableSuccessNotifications(); // Not working on macOS
// -------------------------------------------------------------------------
mix.copy([
     projectPaths.publicSource + '*.config',
     projectPaths.publicSource + '*.php',
     projectPaths.publicSource + '*.txt',
   ], projectPaths.baseDestination)
   .copy(projectPaths.publicSource + '/images', projectPaths.baseDestination + '/images')
   .copy(projectPaths.publicSource + '/error', projectPaths.baseDestination + '/error');
// -------------------------------------------------------------------------
mix.autoload({
  jquery : ['$', 'window.jQuery']
});
// -------------------------------------------------------------------------
mix.js(projectPaths.jsSource + 'app.js', projectPaths.jsDestination)
   .postCss(projectPaths.cssSource + 'appMinimized.css', projectPaths.cssDestination)
   .postCss(projectPaths.cssSource + 'app.css', projectPaths.cssDestination, [
     require('tailwindcss'),
   ])
   .clean({
     verbose : true
   });
// -------------------------------------------------------------------------
if (mix.inProduction()) mix.version();
```
bootstrap.js is not modified, In app.js:

```js
require('./bootstrap');
require('alpinejs');
require('jquery');
...
```

Laravel v8.46.0
Laravel Mix v6.0.19

Npm List:
├── @tailwindcss/aspect-ratio@0.2.1
├── @tailwindcss/forms@0.3.3
├── @tailwindcss/line-clamp@0.2.1
├── @tailwindcss/typography@0.4.1
├── alpinejs@2.8.2
├── axios@0.21.1
├── clean-webpack-plugin@4.0.0-alpha.0
├── jquery@3.6.0
├── laravel-mix-clean@0.1.0
├── laravel-mix@6.0.19
├── lodash@4.17.21
├── postcss-import@14.0.2
├── postcss-preset-env@6.7.0
├── postcss@8.3.0
└── tailwindcss@2.1.4

**Comment by justkidding96** [comment]
@thecrypticace See code below. 

```javascript
mix.setPublicPath('public')
    .copy('resources/img/*', 'public/img/')
    .autoload({
        jquery: ['$', 'window.jQuery'],
        'slick-carousel': ['slick', 'window.slick']
    })
    .extract(['jquery', 'slick-carousel'])
    .sass('resources/scss/app.scss', 'public')
    .js('resources/js/app.js', 'public')
    .version();
```

This give me an error in the console `$(...).slick is not a function` But jQuery works fine.
