### ISSUE TITLE
Laravel Mix breaks with css-loader 6.x

### ISSUE THREAD

**Issue by jacobgraf** [JeffreyWay/laravel-mix#3036]
After running `npm update` this morning, I got a bunch of errors when trying to build. After researching things, it appears that when I ran `npm update`, something updated webpack's css-loader package from 5.x to 6.x which has a lot of breaking changes.

I'm not sure if Laravel Mix allowed `npm update` to update css-loader, or something else, but I'm wondering if anyone has a hotfix in the meantime?

**Comment by thecrypticace** [comment]
We include CSS loader 5.x: https://github.com/JeffreyWay/laravel-mix/blob/420d5d642e3c9a8752d396e75283fe27f0c41e28/package.json#L67

Are you possibly overriding anything in your package.json?

**Comment by jacobgraf** [comment]
This is what I've got...

```
{
    "name": "shopify-natural",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
        "dev": "mix",
        "watch": "mix watch",
        "watch-poll": "mix watch -- --watch-options-poll=1000",
        "hot": "mix watch --hot",
        "prod": "mix --production"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/jacobgraf/gt-shopify.git"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "bugs": {
        "url": "https://github.com/jacobgraf/gt-shopify/issues"
    },
    "homepage": "https://github.com/jacobgraf/gt-shopify#readme",
    "devDependencies": {
        "cross-env": "^7.0.2",
        "laravel-mix": "^6.0.16",
        "less": "^3.12.2",
        "less-loader": "^8.0.0",
        "lodash": "^4.17.20",
        "vue-loader": "^15.9.6",
        "vue-template-compiler": "^2.6.12",
        "webpack": "^5.31.0",
        "webpack-cli": "^4.7.0"
    },
    "dependencies": {
        "@tailwindcss/aspect-ratio": "^0.2.0",
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.3.1",
        "autoprefixer": "^10.0.4",
        "axios": "^0.21.1",
        "postcss": "^8.2.14",
        "tailwindcss": "^2.0.1",
        "tippy.js": "^6.2.7",
        "vue": "^2.6.12",
        "vue-clickaway2": "^2.3.2",
        "vue-currency-filter": "^5.2.0",
        "vue-tippy": "^4.7.2"
    }
}
```

**Comment by thecrypticace** [comment]
🤔 that's super odd. I'll poke around some tonight to see if I can reproduce the problem

**Comment by jacobgraf** [comment]
The only thing I can think of is if any other package is set to pull in css-loader 6.x but I am not sure how to even look into that. I suppose I can look at the package.json for each of the dependencies listed and see if any of them are set to 6.x? ¯\_(ツ)_/¯

**Comment by jacobgraf** [comment]
Not sure if this is it, but I found this in vue-loader/package.json

![CleanShot 2021-07-15 at 15 43 37@2x](https://user-images.githubusercontent.com/146333/125854958-dd55d0a1-4957-49ae-baef-200657372d0d.jpg)

**Comment by thecrypticace** [comment]
Nah, that shouldn't be an issue. In the mean time you can explicitly add `"css-loader": "^5.2"` to your projects package.json file and that should _hopefully_ resolve it.

**Comment by jacobgraf** [comment]
I added it to package.json and that gets me up and running, but man, I wanna know WHAT is allowing the update to 6.x to happen. I went through ALL the packages in package.json and none of them say v6. Any that do have css-loader are set to 5.x like Laravel Mix is.

**Comment by thecrypticace** [comment]
Yeah I'd love to know too because NPM definitely shouldn't allow that to happen

**Comment by PDXfoster** [comment]
Not sure what happened here, but I've been banging my head against the wall on this all morning. Finally ate lunch and came back with a clear head - found that cssloader had updated to 6.0.0 ~19 hours ago with a bunch of breaking changes. 

running 
`npm install --save-dev css-loader@5.2.7`
seems to do the trick for now, and builds are successful.

**Comment by thecrypticace** [comment]
I just did a fresh install and I don't see this behavior but obviously it's happening for several people.

Can you both please provide information on node/yarn versions, OS, etc…?

**Comment by PDXfoster** [comment]
Running locally on: mac os 10.15.7 | Node 16.1.0 | npm 7.11.2
Broke in my prod pipeline on Ubuntu 20.04.2 as well.

Just checked the laravel-mix package.json myself and see the dependency locked to ^5.2.6 --> super weird that npm would allow for this problem. 

`
  "devDependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "cross-env": "^5.2.1",
    "css-loader": "~5.2.7",
    "css-what": "^5.0.1",
    "jquery": "^3.5.1",
    "laravel-mix": "^6.0.24",
    "popper.js": "^1.16.1",
    "postcss": "^8.2.6",
    "resolve-url-loader": "^3.1.2",
    "sass": "~1.32.13",
    "sass-loader": "^10.1.1",
    "vue-loader": "^15.9.6",
    "webpack": "^5.26.3",
    "yargs-parser": "^18.1.3"
  },
`

Thanks for looking into this! 

Again, locking css-loader to 5.2.7 to my package.json file seems to have solved my immediate need, but please let me know if you need anything else to help with reproducing the problem/etc.

**Comment by jacobgraf** [comment]
macOS Big Sur 11.4
Node 16.5.0
npm 7.19.1
Mix 6.0.16

**Comment by ahtinurme** [comment]
Had the same issue, locking the version to 5.2.7 fixed the issue.

macOS Big Sur 11.4
Node 16.4.0
npm 7.18.1
Mix 6.0.25

**Comment by plweil** [comment]
Thank you!! You guys saved my hide! I had no idea why my npm compilations suddenly were going haywire today. All kinds of module build errors on all of my Vue components and sass/css compilations, e.g.,

`Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.`

`ERROR in ./resources/assets/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):`

Locking css-loader to 5.2.7 fixes it. Phew.

MacOS Catalina 10.15.7
Node 12.20.1
npm 7.14.0
Laravel-mix 6.0.25

**Comment by sebastiansulinski** [comment]
Same issue here - using `css-loader@^5.2.7` seem to have worked.

**Comment by OliverGrimsley** [comment]
Had same issue - I updated NPM and got several of these errors:
`
ERROR in .[file] (./node_modules/css-loader/dist/cjs.js??clonedRuleSet-12[0].rules[0].use[1]!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??clonedRuleSet-12[0].rules[0].use[2]!./node_modules/sass-loader/dist/cjs.js??clonedRuleSet-12[0].rules[0].use[3]!./node_modules/vue-loader/lib/index.js??vue-loader-options!./resources/assets/js/components/formcomponents/dropdownMenu.vue?vue&type=style&index=0&id=54d45544&lang=scss&scoped=true&)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: Invalid options object. CSS Loader has been initialized using an options object that does not match the API schema.
...
`

Gave up Friday after searching - this AM deleted node_modules, removed all sass and css-loader references in package.json, reinstalled node modules.  After running Mix, Mix noted it needed to install a dependency (sass-loader).  Ran `npx mix watch` again - now it failed with a ton of 
`
ERROR in ./resources/assets/js/components/[path]/[component].vue 4:0-94
Module not found: Error: Can't resolve 'css-loader' in '[project root directory]'
`
Did as per above `npm install --save-dev css-loader@5.2.7` and now it compiles fine.

Adding this here only because when I searched for my original error, this article did not appear

**Comment by maximal** [comment]
Have this issue too. Using:

```
	"resolve-url-loader": "^4.0",
	"sass": "^1.35.2",
	"sass-loader": "^8.0.2",
```

**Comment by jacobgraf** [comment]
Now getting this...

`[webpack-cli] Error: Cannot find module 'sass-loader'`

and

`[webpack-cli] Error: Cannot find module 'stylus-loader'`

Manually installing both fixes things, but eeks.

**Comment by thecrypticace** [comment]
That shouldn't happen unless you call `.sass()` or `.stylus()`. Alright I'll take another look later today. @JeffreyWay Are you seeing this too? I think I missed something here.

**Comment by thecrypticace** [comment]
Yep, I did. We always include sass/less/etc rules even if you don't have the loader installed. We need to check for them now before we can include the rule. Sorry for all the trouble.

**Comment by maximal** [comment]
@thecrypticace, @JeffreyWay, any thoughts about when the fix is going to be available in future releases?

**Comment by thecrypticace** [comment]
I opened a PR. I still need to test it myself on a few different minimal projects but I can't at the moment.

**Comment by JeffreyWay** [comment]
@maximal @jacobgraf Can you guys bump to 6.0.27 and let us know if you're still seeing issues?

**Comment by jacobgraf** [comment]
@JeffreyWay fixed for me!

**Comment by JeffreyWay** [comment]
@jacobgraf. Awesome. Thanks @thecrypticace.

**Comment by maximal** [comment]
@JeffreyWay, sorry for the delay. Can confirm that build passes fine after the upgrade to v6.0.27.

**Comment by plweil** [comment]
@JeffreyWay same here. Build passes after bumping to v.6.0.27. Thank you!
