### ISSUE TITLE
Cannot export a function after update from 0.8 to 0.9

### ISSUE THREAD

**Issue by donnysim** [JeffreyWay/laravel-mix#625]
After upgrading from laravel mix to 0.8 to 0.9 I'm having a compilation error when importing file with export of a function.

Have two files

1 - test.js:

```
import fn from './test2';
```

2 - test2.js:
```
export default function () {

}
```

compiling `test.js` crashes with error

```
Module parse failed: D:\Laragon\admin-panel\node_modules\babel-loader\lib\index.js?cacheDirectory!D:\Laragon\admin-panel\test2.js Cannot read property 'name' of null
You may need an appropriate loader to handle this file type.
TypeError: Cannot read property 'name' of null
    at Parser.walkFunctionDeclaration (D:\Laragon\admin-panel\node_modules\webpack\lib\Parser.js:539:39)
    at Parser.walkStatement (D:\Laragon\admin-panel\node_modules\webpack\lib\Parser.js:436:32)
    at Parser.walkExportDefaultDeclaration (D:\Laragon\admin-panel\node_modules\webpack\lib\Parser.js:613:9)
    at Parser.walkStatement (D:\Laragon\admin-panel\node_modules\webpack\lib\Parser.js:436:32)
    at Parser.walkStatements (D:\Laragon\admin-panel\node_modules\webpack\lib\Parser.js:419:9)
    at Parser.parse (D:\Laragon\admin-panel\node_modules\webpack\lib\Parser.js:1193:8)
    at doBuild (D:\Laragon\admin-panel\node_modules\webpack\lib\NormalModule.js:288:17)
    at runLoaders (D:\Laragon\admin-panel\node_modules\webpack\lib\NormalModule.js:206:11)
    at D:\Laragon\admin-panel\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (D:\Laragon\admin-panel\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (D:\Laragon\admin-panel\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at D:\Laragon\admin-panel\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at context.callback (D:\Laragon\admin-panel\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\Laragon\admin-panel\node_modules\babel-loader\lib\index.js:159:14
    at D:\Laragon\admin-panel\node_modules\babel-loader\lib\fs-cache.js:76:24
    at D:\Laragon\admin-panel\node_modules\babel-loader\lib\fs-cache.js:31:14
    at Gunzip.onEnd (zlib.js:213:5)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Anyone has any ideas whos problem this is? Did webpack 2.3 break it or something to do with babel? It worked before.

Everything is freshly reinstalled.

**Comment by donnysim** [comment]
I'm confused as event installing fresh laravel-mix 0.8.2 is causing this when previously it did not.

**Comment by donnysim** [comment]
Never mind, must delete yarn.lock otherwise something goes awfully wrong.
