### ISSUE TITLE
Upgrade to 0.9 breaks file-loader. Can't load svgs.

### ISSUE THREAD

**Issue by adiachenko** [JeffreyWay/laravel-mix#614]
- Laravel Mix Version: 0.9.2
- Node Version (`node -v`): v6.9.2
- NPM Version (`npm -v`): 3.10.9
- OS: Windows 10

### Description:

```
 error  in ./resources/assets/svg/zondicons/close.svg

Module build failed: TypeError: url.replace is not a function
    at Object.interpolateName (C:\app\ln\node_modules\loader-utils\index.js:276:13)
    at Object.module.exports (C:\app\ln\node_modules\file-loader\index.js:30:24)

 @ ./~/babel-loader/lib?cacheDirectory!./~/vue-loader/lib/selector.js?type=script&index=0!./resources/assets/js/components/Datepicker/Datepicker.vue 21:0-57
 @ ./resources/assets/js/components/Datepicker/Datepicker.vue
 @ ./resources/assets/js/app.js
 @ multi ./resources/assets/js/app.js

```

### Steps To Reproduce:

```
import closeIcon from '../../../svg/zondicons/close.svg'
```

**Comment by adiachenko** [comment]
BTW, I don't know whether this i the source of the issue

```
To prevent file name collisions, vendor assets will now be moved to a dedicated vendor folder. 
```

but I find these shenanigans with folder segregation questionable. You won't have naming conflicts anyway if you hash all assets so why introduce unnecessary complications?

**Comment by JeffreyWay** [comment]
This was from a PR a few weeks ago. I believe it was because you can end up with vendor assets that have the same name as your own assets. So this prevents file overwriting. 

I'll have to check exactly why you're seeing this issue.

**Comment by njbarrett** [comment]
I'm seeing this error also since updating to 0.9.2

**Comment by manniL** [comment]
I receive this error too, but only on my production server. Then I updated NodeJS to v6.10.1 and npm to 4.1.2. Finally, I nuked my node_modules folder. Then it worked for me.

**Comment by adiachenko** [comment]
I already tried nuking `node_modules` with no results. There is some other quirk here.

**Comment by adiachenko** [comment]
Gotcha! After @manniL suggestion I figured this might something to do with differences in `node_modules` structure between yarn and npm. Therefore, temporarily switching to npm is another confirmed way to solve the issue.

In the end, it seems like [string replace here](https://github.com/JeffreyWay/laravel-mix/blob/v0.9.0/setup/webpack.config.js#L170) needs to be adjusted accordingly. Ping @KristofMorva.

**Comment by KristofMorva** [comment]
@adiachenko I can't really see it yet, what's the difference between `npm` and `yarn` structure? I have updated every package, and SVG files are copied well for me. I thought maybe https://github.com/webpack/loader-utils has changed, and it passes a non-string parameter (which will have no `replace` method), but the tests seem to be unchanged in that package.

**Comment by adiachenko** [comment]
@KristofMorva It doesn't seem like the source of the issue was that closure by itself.

I revisited it again and tried to break it down to more simple example.

Assume we've installed packages with yarn 0.21.3 on Windows 10. Whether you actually run the build on yarn or npm does not matter.

This will work:

```
    {
        test: /\.(woff2?|ttf|eot|svg|otf)$/,
        loader: 'file-loader',
        options: {
            name: 'fonts/[name].[ext]?[hash]',
            publicPath: Mix.options.resourceRoot
        }
    },

```

But this will give you `TypeError: url.replace is not a function`:

```
    {
        test: /\.(woff2?|ttf|eot|svg|otf)$/,
        loader: 'file-loader',
        options: {
            name: path => {
              return 'fonts/[name].[ext]?[hash]'
            },
            publicPath: Mix.options.resourceRoot
        }
    },
```
And here [is the point in code where an error occurs](https://github.com/webpack/loader-utils/blob/master/lib/interpolateName.js#L65) in `loader-utils`.

**Comment by adiachenko** [comment]
Okay, I've solved the issue. 

It seems like you need to nuke your `yarn.lock` file.

The reason why there were discrepancies between different dependency managers is because npm installed `loader-utils` 1.0.2 while yarn installed 0.2.6 from the lock file.

Once loader-utils is bumped to the latest version, the issue is gone.

Sorry, @KristofMorva for suspecting this might have something to do with your PR. 😄

**Comment by adiachenko** [comment]
@JeffreyWay Yes, indeed. Basically, it's a minor issue with `yarnpkg` workflow rather than Mix.

**Comment by adiachenko** [comment]
@JeffreyWay On a second though, this might have been avoided if Mix bumped `file-loader` version to 0.10.1 between releases. I'll create pull request for this in a moment.
