### ISSUE TITLE
TypeError: arguments[i].apply is not a function with mix.copy()

### ISSUE THREAD

**Issue by tlshaheen** [JeffreyWay/laravel-mix#742]
- Laravel Mix Version: 0.11.0
- Node Version: 6.10.2
- NPM Version: 3.10.10 but not using NPM, using Yarn v0.23.2
- OS: macOS 10.12.4

### Description:
I have `mix.copy('resources/assets/css', 'public/css');`. This worked in v0.10.0 with no errors. But when I upgrade to v0.11.0, I now get a `TypeError: arguments[i].apply is not a function` error. If I remove `mix.copy()` from my mix file, `yarn run production` works just fine.

I've tried changing it to `mix.copyDirectory()`, but the error remains the same. 

What am I doing wrong?

### Steps To Reproduce:

**webpack.mix.js**
````
let mix = require('laravel-mix').mix;

mix.copy('resources/assets/css', 'public/css');
````

**.babelrc**
````
{
  "env": {
    "development": {
      "presets": ["latest", "stage-2"]
    },
    "production": {
      "presets": [
        "latest",
        "stage-2",
        ["es2015", { "modules": false }]
      ]
    },
    "test": {
      "presets": ["latest", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
````

**package.json**
````
{
  "private": true,
  "scripts": {
    "webpack": "cross-env NODE_ENV=development webpack --progress --hide-modules --config=webpack.config.js",
    "dev": "cross-env NODE_ENV=development webpack --watch --progress --profile --hide-modules --config=webpack.config.js",
    "hmr": "cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=webpack.config.js",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules --config=webpack.config.js",
    "test": "npm run unit",
    "unit": "cross-env NODE_ENV=test karma start karma.config.js --single-run",
    "lint": "eslint --ext .js,.vue ./resources/assets/js/components ./tests/js/unit/specs --output-file=./eslintresults.html --format=html --color"
  },
  "dependencies": {
    "babel-core": "^6.24",
    "babel-loader": "^6.4",
    "babel-preset-env": "^1.2",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-latest": "^6.24.0",
    "babel-preset-stage-2": "^6.22.0",
    "bootstrap-sass": "^3.3",
    "cross-env": "^3.2.3",
    "es6-promise-promise": "^1.0.0",
    "filestack-js": "^0.2.1",
    "handlebars": "^4.0",
    "html5sortable": "^0.3.0",
    "inject-loader": "^2.0.1",
    "intersection-observer": "^0.2.1",
    "jquery": "^3.2.1",
    "laravel-elixir": "^5.0.*",
    "laravel-elixir-handlebars": "git+https://github.com/Ikstar/laravel-elixir-handlebars.git",
    "laravel-mix": "^0.11.0",
    "lodash": "^4.17",
    "moment-timezone": "^0.5.11",
    "node-sass": "^4.5.2",
    "purifycss-webpack": "^0.5.0",
    "uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony",
    "vue": "^2.2",
    "vue-infinite-loading": "^2.0.3",
    "vue-resource": "1.2.1",
    "vue-strap": "github:tlshaheen/vue-strap#5e2b3c4eb50e49f10500bd751fff92564eea7a3c",
    "vuex": "^2.2",
    "webpack": "^2.3",
    "webpack-manifest-plugin": "^1.1.0",
    "webpack-merge": "^4.1"
  }
}
````
**Full error message**
````
$ yarn run production
yarn run v0.23.2
$ cross-env NODE_ENV=production webpack --progress --hide-modules --config=webpack.config.js
Copying resources/assets/css to /MYDIRECTORY/platform/public/css
/MYDIRECTORY/platform/node_modules/webpack/bin/webpack.js:315
		throw e;
		^

TypeError: arguments[i].apply is not a function
    at Compiler.apply (/MYDIRECTORY/platform/node_modules/tapable/lib/Tapable.js:306:16)
    at webpack (/MYDIRECTORY/platform/node_modules/webpack/lib/webpack.js:32:19)
    at processOptions (/MYDIRECTORY/platform/node_modules/webpack/bin/webpack.js:305:14)
    at Object.<anonymous> (/MYDIRECTORY/platform/node_modules/webpack/bin/webpack.js:363:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:508:3
error Command failed with exit code 1.
````

**Comment by TitasGailius** [comment]
I'm having the same issue.

**Comment by JeffreyWay** [comment]
Hmm, I just tested your `mix.copy('resources/assets/css', 'public/css');` line on a fresh installed, and there were no errors. 

Can anyone pinpoint when/where this is happening? I can't reproduce.

**Comment by 1e4** [comment]
I too have just had this problem

`package.json`

    {
      "private": true,
      "scripts": {
        "dev": "node ./node_modules/cross-env/dist/bin/cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=webpack.config.js",
        "watch": "node ./node_modules/cross-env/dist/bin/cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=webpack.config.js",
        "watch-poll": "node ./node_modules/cross-env/bin/cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --watch-poll --progress --hide-modules --config=webpack.config.js",
        "hot": "node ./node_modules/cross-env/dist/bin/cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=webpack.config.js",
        "production": "node ./node_modules/cross-env/dist/bin/cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=webpack.config.js"
      },
      "devDependencies": {
        "axios": "^0.15.3",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^3.2.3",
        "jquery": "^3.1.1",
        "laravel-mix": "0.*",
        "lodash": "^4.17.4",
        "vue": "^2.1.10"
      },
      "dependencies": {
        "@sergiovilar/jquery-pjax": "^1.7.1-0",
        "bootstrap-daterangepicker": "^2.1.25",
        "buble-loader": "^0.4.0",
        "font-awesome": "^4.7.0",
        "jquery": "^2.2.4",
        "jquery-sortable": "^0.9.13",
        "jquery-ui": "^1.12.1",
        "jquery-ui-dist": "^1.12.1",
        "moment": "^2.18.1",
        "nestedSortable": "ilikenwf/nestedSortable",
        "noty": "^2.4.1",
        "tinymce": "^4.5.7",
        "tinyscrollbar": "^2.4.2"
      }
    }

Error Log


    root@root /c/xampp/htdocs/dir (master) $ yarn run dev
    yarn run v0.24.5
    $ node ./node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=webpack.config.js
    Copying ./node_modules/tinymce/skins to C:\xampp\htdocs\dir\public\js\skins
    Copying ./node_modules/tinymce/plugins to C:\xampp\htdocs\dir\public\js\plugins
    C:\xampp\htdocs\dir\node_modules\webpack\bin\webpack.js:315
                    throw e;
                    ^

    TypeError: arguments[i].apply is not a function
        at Compiler.apply (C:\xampp\htdocs\dir\node_modules\tapable\lib\Tapable.js:306:16)
        at webpack (C:\xampp\htdocs\dir\node_modules\webpack\lib\webpack.js:32:19)
        at processOptions (C:\xampp\htdocs\dir\node_modules\webpack\bin\webpack.js:305:14)
        at Object.<anonymous> (C:\xampp\htdocs\dir\node_modules\webpack\bin\webpack.js:363:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.runMain (module.js:604:10)
        at run (bootstrap_node.js:390:7)
        at startup (bootstrap_node.js:150:9)
        at bootstrap_node.js:505:3
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
    root@root /c/xampp/htdocs/dir (master) $

**Comment by 1e4** [comment]
@tlshaheen Did you recently upgrade your Laravel?

I updated my scripts section of `package.json` to read


    "scripts": {
      "dev": "npm run development",
      "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
      "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
      "watch-poll": "npm run watch -- --watch-poll",
      "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
      "prod": "npm run production",
      "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },

Seems like it could be that your config for webpack is outdated.
